Repository Tech-With-Tim/twtcodejam.net, pull requests merged in 2021-09, with the labels that each got.

#70 Update notification messages
  TWT/apps/timathon/views/create_team.py
  TWT/apps/timathon/views/submission_list_view.py
Labels: non-code changes

#69 new config, change votes ordering, black linting
  TWT/apps/timathon/models/submission.py
  TWT/apps/timathon/views/judge/judge.py
  TWT/apps/timathon/views/submission_view.py
  TWT/discord.py
  TWT/settings.py
  config.py
  requirements.txt
Labels: backend

#73 Added Youtube Link field to Challenge and displaying it in the timathon history page
  TWT/apps/challenges/models/challenge.py
  TWT/templates/timathon/codejam_listView.html
Labels: enhancement, frontend, backend
